### ISSUE TITLE
Website Sitemap Needed

### ISSUE THREAD

**Issue by DavidRies** [CISecurity/OVALRepo#1]
We need a website sitemap including:
- pages on site organized hierarchically
- a brief description of the content that will be on each page and/or link to source of content

**Comment by adammontville** [comment]
Is this issue blocking anyone right now?

**Comment by adammontville** [comment]
The initial thought I have on this is that we don't need a ton of pages.  The landing page should probably have the most commonly used downloads on it.  Something akin to the table of links here: https://oval.mitre.org/rep-data/index.html.

Rather than having a separate page for mailing list signup, we should put links to the mailing list subscription on the landing page.

People are probably going to want some level of instruction if they're going to be cloning/building on their own, so a separate instruction page could be useful.

**Comment by DavidRies** [comment]
Yes, instruction pages for content contributors and content consumers. Also, I think you should move the top contributors awards/listing pages over. They seem to like that.

**Comment by blakefrantz** [comment]
@adammontville should this be reassigned to @stekel?

**Comment by adammontville** [comment]
That's a good idea, though I think this can be closed - leaving open until more people have seen what @stekel has cooked up.

**Comment by stekel** [comment]
Now that everyone has had a chance to see the site... is this still necessary?

**Comment by GunnarEngelbach** [comment]
Nope.

This was originally intended as a design step to help define what was 
needed for the web site.  This is now OBE.

**Comment by stekel** [comment]
Cool. Closing.
