### ISSUE TITLE
no output for build_oval_definitions_file.py

### ISSUE THREAD

**Issue by koehoorn** [CISecurity/OVALRepo#1118]
Hi,
im trying to compile a list of linux vulnerability checks for my linux machines.
so im trying these suggestions:
https://github.com/CISecurity/OVALRepo/tree/master/scripts#scripts-for-content-use
but im getting an empty file.

How to get the actual oval checks  ?

```
# python3 build_oval_definitions_file.py -o all.linux.vulnerability.xml --family linux --class vulnerability
# cat all.linux.vulnerability.xml
<?xml version="1.0" encoding="UTF-8"?>
<oval_definitions
        xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5"
        xmlns:oval="http://oval.mitre.org/XMLSchema/oval-common-5"
        xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
        xsi:schemaLocation="http://oval.mitre.org/XMLSchema/oval-common-5 oval-common-schema.xsd http://oval.mitre.org/XMLSchema/oval-definitions-5 oval-definitions-schema.xsd">

        <generator>
                <oval:product_name>CIS OVAL Repository</oval:product_name>
                <oval:product_version>0.1</oval:product_version>
                <oval:schema_version>5.11.2</oval:schema_version>
                <oval:timestamp>2017-10-16T09:10:21</oval:timestamp>
        </generator>

</oval_definitions>
```

**Comment by wmunyan** [comment]
Merijn, 
Thanks for your issue.  The problem here is that there is no family defined in OVAL for "linux".  You need to use `--family unix` to get both Unix and Linux content.  Give that a try and let us know how that works out.  Also, if you'd rather just download full bundles rather than scripting them, you can go to the [OVAL Repository Website](https://oval.cisecurity.org/repository/download), select the options you want, and download bundles from there.

Hope that helps!
Bill M (CIS)

**Comment by koehoorn** [comment]
thanks for your reply, 
i will look on the website for complete bundles and probably use that instead.

the build_oval_definitions_file.py script still does not return any output for me. 
```
[scripts] > python3 build_oval_definitions_file.py -o unix.xml --family unix --class vulnerability
INFO: Found 0 matching OVAL definitions
INFO: Writing OVAL definitions to unix.xml
INFO: Completed in 00:00:02!
[scripts] > python3 build_oval_definitions_file.py --all_definitions -o all.xml -v
INFO: Found 0 matching OVAL definitions
INFO: Writing OVAL definitions to all.xml
INFO: performing schema validation
INFO: schema validation successful
INFO: Completed in 00:00:02!
```

**Comment by DavidRies** [comment]
Hi Merjin,

That is odd. I just ran your exact command and it worked as expected:

````
python3 build_oval_definitions_file.py -o unix.xml --family unix --class vulnerability
INFO: Rebuilding oval_definitions index completed (30718 definitions)
INFO: Found 5357 matching OVAL definitions
INFO: Finding downstream OVAL ids for all definitions
INFO: Rebuilding oval_elements index completed (238608 elements)
INFO: Found 25401 downstream OVAL ids
INFO: Finding paths for 30758 OVAL elements
INFO: Generating OVAL definition file with 30758 elements
INFO: Writing OVAL definitions to unix.xml
INFO: Completed in 00:06:16!
````

You can certainly download the packages from the website instead of building them yourself.

If you want to build them yourself, I would recommend trying the following:

1. confirm that you have the content files locally (do a git pull, then check your local ./repository folder to make sure it seems to have 1000s of xml files like https://github.com/CISecurity/OVALRepo/tree/master/repository)

2. confirm that the index is building properly by running `python3 web_update_indexes.py --nocache`. You should see something status messages like this: `INFO: Rebuilding oval_definitions index |----> xxxxx definitions`

3. run `python3 web_get_repository_stats.py` to confirm that the index has detected files for unix, etc.

Let us know what you find out!

**Comment by koehoorn** [comment]
the index rebuild took 16 minutes. 
its likely that i interrupted that process the first time, since it shows no output for minutes at a time.

```
[16:18 scripts] > python3 web_update_indexes.py --nocache







{
    "MESSAGES": [
        {
            "DEFINITIONS": "index updated"
        },
        {
            "ELEMENTS": "index updated"
        },
        {
            "REVISIONS": "index updated"
        },
        {
            "TIME": "00:16:01"
        }
    ]
}
[16:34 scripts] > python3 build_oval_definitions_file.py -o unix.xml --family unix --class vulnerability
INFO: Found 5357 matching OVAL definitions
INFO: Finding downstream OVAL ids for all definitions
INFO: Found 25401 downstream OVAL ids
INFO: Finding paths for 30758 OVAL elements
INFO: Generating OVAL definition file with 30758 elements
INFO: Writing OVAL definitions to unix.xml
INFO: Completed in 00:00:31!
```

works a lot better now, thanks again for the usage tips, solving this.

**Comment by DavidRies** [comment]
Glad to hear it's resolved! It sounds like the build scripts need to be revised to issue a warning if the indexing isn't complete. Thanks for the feedback!
