### ISSUE TITLE
oval:org.cisecurity:tst:3756 "check" should be "all"

### ISSUE THREAD

**Issue by zevanty** [CISecurity/OVALRepo#1225]
In oval:org.cisecurity:tst:3756:
```
<registry_test xmlns="http://oval.mitre.org/XMLSchema/oval-definitions-5#windows" check="at least one" check_existence="at_least_one_exists" comment="Check if Wireshark version is greater than or equal 2.2.0 and less than 2.2.7" id="oval:org.cisecurity:tst:3756" version="1">
  <object object_ref="oval:org.mitre.oval:obj:6871" />
  <state state_ref="oval:org.cisecurity:ste:2766" />
  <state state_ref="oval:org.cisecurity:ste:2767" />
</registry_test>
```
I believe `check` should be `all` instead of `at least one`. Can someone confirm? If so, I can open a pull request against this test and some other tests that I've found with a similar issue.

**Comment by AlChua** [comment]
I think "at least one" is also correct since the version being checked is located on a specific registry entry.
		  <hive>HKEY_LOCAL_MACHINE</hive>
		  <key>SOFTWARE\Microsoft\Windows\CurrentVersion\Uninstall\Wireshark</key>
		  <name>DisplayVersion</name>

**Comment by zevanty** [comment]
Is that how the value of `check` is based on? According to the OVAL guide in page 29 (don't know if there is a newer one): http://oval.mitre.org/language/version5.11/oval-language-specification_12-18-2014.pdf
Enumeration Value Description
all The final result is ‘true’ only if all of the individual results under consideration are ‘true’.
at least one The final result is ‘true’ only if one or more of the individual results under consideration are ‘true’.
My interpretation is that everything under the `registry_test` needs to apply for the test, since `oval:org.cisecurity:ste:2766` checks for the `greater than or equal` state and `oval:org.cisecurity:ste:2767` checks for the `less than` state. If only one of them needs to be true, then you can have a version that falls out of bound with the intended check (in this example, v2.0.0 will apply since it's technically less than 2.2.7)

**Comment by kemanik** [comment]
I try to install 32 and 64-bit versions of Wireshark on one system. One of the version rewrites the other. Check="all" is needed when two or more versions of product is installed and all of them may be vulnerable. If on the system could be installed only one version then the value of check parameter doesn't matter.

**Comment by zevanty** [comment]
So you're saying `check` only applies to the architecture of the application installed, not based on the `<state>` tags? That really doesn't sound like what is stated in the OVAL guide.

**Comment by gheaton** [comment]
It seems to me that the comment & OVAL spec agree with zevanty here.

The comment says "Check if Wireshark version is greater than or equal 2.2.0 and less than 2.2.7", this suggests that both states must yield a result of 'true' in order for the test to result 'true'.

The OVAL spec gives the CheckEnumeration value of "at least one" a description of "The final result is 'true' only if one or more of the individual results under consideration are 'true'." and the value "all" as "The final result is 'true' only if all of the individual results under consideration are 'true'."

I may be mistaken with my interpretation here, but that translates to me as "at least one" being "OR", and "all" being "AND".

This also makes more sense with the underlying logic itself: if we want to select all versions between these two states (and inclusive for 2.2.0), we need the intersection of these sets. I believe the union of these two sets results in a test matching all possible versions, which is highly problematic.

**Comment by AlChua** [comment]
I think it wouldn't be problematic since as per documentation, every "tests" has an optional "state_operator" attribute and it has a default value of "AND".

`<xsd:documentation>The optional state_operator attribute provides the logical operator that combines the evaluation results from each referenced state on a per item basis.  Each matching item is compared to each referenced state. The result of comparing each state to a single item is combined based on the specified state_operator value to determine one result for each item. Finally, the results for each item are combined based on the specified check value.  Note that if the test does not contain any references to OVAL States, then the state_operator attribute has no meaning and can be ignored during evaluation. Referencing multiple states in one test allows ranges of possible values to be expressed. For example, one state can check that a value greater than 8 is found and another state can check that a value of less than 16 is found.  In this example the referenced states are combined with a state_operator = 'AND' indicating that the conditions of all referenced states must be satisfied and that the value must be between 8 AND 16. The valid state_operation values are explained in the description of the OperatorEnumeration simple type.</xsd:documentation>`

> Referencing multiple states in one test allows ranges of possible values to be expressed. For example, one state can check that a value greater than 8 is found and another state can check that a value of less than 16 is found.  In this example the referenced states are combined with a state_operator = 'AND' indicating that the conditions of all referenced states must be satisfied and that the value must be between 8 AND 16.

I did some test on the OVAL definition with a 2.2.11 wireshark version installed and the registry_test returned a false result. I think this is because of the state_operator="AND" that indicates that both states should be satisfied.

**Comment by kemanik** [comment]
"Check" parameter plays the role in case of several items. But when you have one item in object and two states we should pay attention to state_operator but the dafault value is AND and that's why nothing needed to be modified.

**Comment by gheaton** [comment]
Thanks AlChua, that makes sense

**Comment by zevanty** [comment]
I think I understand the situation. Thanks for the explanation. I'll close this issue.
