### ISSUE TITLE
We have to increase version for updated definitions, tests. objects, states, variables

### ISSUE THREAD

**Issue by SergeyArtykhov** [CISecurity/OVALRepo#124]
I have updated oval_org.mitre.oval_def_29058.xml some time ago. This definition was deprecated (PR-118). The version for this definition was not increased. This is very bad for repository integrity and outer syncs.

https://github.com/CISecurity/OVALRepo/blob/master/repository/definitions/inventory/oval_org.mitre.oval_def_29058.xml

Best Regards,
Sergey

**Comment by wmunyan** [comment]
Sergey, 
Thanks for the feedback.  We make every effort to increase the version number on applicable definitions, tests, objects and states.  This one got missed because of the deprecation and it was an oversight by me in the processing of the request. 

I have added status change information and incremented the version number for this definition, and committed the changes.

Thanks again for the feedback and all your contributions to the repository!
Cheers, 
-Bill M.
