### ISSUE TITLE
oval:org.cisecurity:def:5113 exists twice in the generated XMLs

### ISSUE THREAD

**Issue by Memnarch** [CISecurity/OVALRepo#1574]
As far as i can see, definition "oval:org.cisecurity:def:5113" is added twice to a generated oval xml.
It exists as Vulnerabilty(version 8)
 OVALRepo/repository/definitions/vulnerability/oval_org.cisecurity_def_5113.xml 
and as Inventory (version 9)
 OVALRepo/repository/definitions/inventory/oval_org.cisecurity_def_5113.xml 

I think version 8 was supposed to be removed as it seems the definition was declared a Vulnerability in the past by accident.

Either way, the generated file will contain both definitions. Interpreter that evaluate the versions will ignore the older one and those who don't (like Ovaldi) will simply throw an error

**Comment by Memnarch** [comment]
Sure, i can do that. WIll make a pull request: From what i can tell, i only have to remove the file?
Haven't found anything specifically after a brief look at the reources of/linked in Readme

**Comment by DavidRies** [comment]
Yes, in this case all you have to do is remove the file. Normally, you would need to ensure that removing the file did not break any content that referenced it or orphan content that it referenced and was not referenced by anything else, but in this case, because a later version of the definition ID will remain in the repo, there is not danger of that.

**Comment by Memnarch** [comment]
But this will have to wait until tomorrow, i'm sorry

**Comment by Memnarch** [comment]
As the Pullrequest was merged, i'll close this issue.
