### ISSUE TITLE
No new vulnerability definitions since 2019-03-01

### ISSUE THREAD

**Issue by mirostauder** [CISecurity/OVALRepo#1696]
Is this project being abandoned?

**Comment by DavidRies** [comment]
Hi @mirostauder,

No, this project is not abandoned. Many definitions have been contributed since 3/1/2019, as recently as last week (see https://github.com/CISecurity/OVALRepo/pulls?q=is%3Apr+is%3Aclosed).

This is a community project that relies on contributions of OVAL definitions from the community. And, while it is widely used, we don't get much feedback from the community about who specifically is using it, what specific content they require, etc. 

I'm guessing there is some specific content that you (or your company) uses that hasn't been updated in the last several weeks? I encourage you to tell us a bit more about your company, how you use the repository and your specific needs so we can help.

-David

**Comment by obas21** [comment]
I was about to open a new issue for the same thing. I think this is related specifically to Windows Vulnerability definitions. There were a number of new checks added 3/1/2019, but none of them have moved past "DRAFT" status.

**Comment by Memnarch** [comment]
Same here. We(Our Company) use oval on windows to scan for Vulnerabilities in a product we sell to other companies.

Besides the mentioned issues, it seems the windows related definitions on https://oval.cisecurity.org/repository/download haven't been updated since march. AT least that's what the timestamp tells.

**Comment by iangfi** [comment]
We are particularly interested in Windows CVEs, and it's quite strange that none have been found in 3 months.

**Comment by Memnarch** [comment]
It seems worse? Just checked https://oval.cisecurity.org/repository/download
NO uploads on ANY platform for 3 month. March 8th 2019 is the most recent egneration. SInce then, nothing.

**Comment by zport** [comment]
Hi all,

Thanks for bringing this to our attention. It does look like there's an issue with updating the oval.cisecurity.org site at the moment which we're working to fix. We're hoping to have that repaired by the end of next week but I'll keep you posted if that changes. In the meantime, there are new definitions that are available through GitHub that can be seen at the link David posted above. If you have any questions please feel free to ask them here.

Best,

Zack

**Comment by DavidRies** [comment]
It seems there are 3 issues:

### 1. Download links at oval.cisecurity.org are not being updated regularly
CIS generates these packages and posts them to https://oval.cisecurity.org/repository/download for the convenience of the community. It sounds like Zack is looking into resolving this. 

Please note: you do not need to use these prepackaged downloads. If you'd like, you can build your own packages directly from the repository content using the tools included in this repository by following this documentation: https://github.com/CISecurity/OVALRepo/blob/master/scripts/README.md#scripts-for-content-use

### 2. Definition status is not being updated 
It is noted above that some packages are still marked DRAFT. CIS also updates these definition status values. I'm not sure exactly what the policy is concerning when to update them. Zack, can you look into this too? Perhaps this is a symptom of the same issue that's causing the builds not to happen?

### 3. The latest Windows CVE definitions have not been submitted to the repository
As you probably know, this is a community project that relies on contributions of OVAL definitions from the community. From time to time, contributors change--individuals and organizations stop contributing and others start. 

We are currently in the middle of one of these transitions. DTCC was the primary contributor of Windows CVE definitions for quite some time. They are no longer contributing content. Jerome Athias and others have contributed definitions in the interim. My company, Joval, primarily contributes Cisco content. But, we did create and contribute a large number of Windows definitions in March. We plan to contribute more, on an ongoing basis in a timely fashion, but--as you may know--it is a lot of work. We are building automation, tooling, and processes and putting other resources in place to create and contribute this content. If others are interested in contributing OVAL content, collaborating with us on creating this content and/or sponsoring this effort of ours, that would certainly help.

Best, 
David Ries

**Comment by zport** [comment]
We can certainly look into the status issue as well. Thanks for the clarification!

**Comment by wmunyan** [comment]
@DavidRies for the status updates, we process them every week on Fridays, and updates occur after 2 weeks for each successive status, i.e. a definition will sit in "draft" for 2 weeks, then be updated to "interim" and so on.  The fact that this isnt being seen in the downloads is a product of the 1st issue.  Apparently the pipeline from the scripts generating the content and them being served up has been broken.  It's the priority for the team and they're working it now.

**Comment by zport** [comment]
@DavidRies and @wmunyan , I also just spot-confirmed with a few of the recent submissions that they have been moving through the statuses and are at the Accepted status where they should be. Like Bill said, looks like it's a result of the first issue.

**Comment by obas21** [comment]
Has there been any update on the first issue?
 
 
----- Original message -----From: Zachary Port <notifications@github.com>To: CISecurity/OVALRepo <OVALRepo@noreply.github.com>Cc: obas21 <dsabo@us.ibm.com>, Comment <comment@noreply.github.com>Subject: [EXTERNAL] Re: [CISecurity/OVALRepo] No new vulnerability definitions since 2019-03-01 (#1696)Date: Fri, Jun 14, 2019 10:54 AM 
@DavidRies and @wmunyan , I also just spot-confirmed with a few of the recent submissions that they have been moving through the statuses and are at the Accepted status where they should be. Like Bill said, looks like it's a result of the first issue.

**Comment by wmunyan** [comment]
@obas21 the first 2 issues above are related, and the scripts/pipeline to update the repository downloads has been fixed and is running.  What's downloadable on the website is up-to-date.

Cheers, 
-Bill M (CIS)

**Comment by DavidRies** [comment]
Hello @obas21, we are preparing to submit a large number of Windows OS CVE checks (~350 CVEs), catching up to the current patch Tuesday. We are currently testing the content and making it available for community review. Would you be interested in reviewing it? If so, please contact me at ries@jovalcm.com.

**Comment by nrathaus** [comment]
We can close this thread, its not relevant anymore.
