### ISSUE TITLE
Minimum Schema Version: determine approach, script, maintain

### ISSUE THREAD

**Issue by DavidRies** [CISecurity/OVALRepo#18]
We need to be able to generate packages based on schema version. To do that, I need something like the following in every OVAL definitions file:
````
/definition/metadata/oval_repository/<min_schema_version>5.8</min_schema_version>
````
It needs to be added to all existing defs and all going forward. Also, we need to be able to maintain that. This needs a little thinking in terms of process. 

To get started, we probably need:
- a script that can determine the min schema version required for 1 definition and
 - optionally add/update it in file if it's missing or incorrect
- add this as a required field to the repository metadata schema
- add repo metadata schema to the schemas folder and validation library so we can validate it

That would be a good start. Then, we need someone to think about how this will be maintained/checked going forward. E.g.:
- will contributors have to input this or will CIS run scripts to populate this?
- what happens when an element changes that is referenced by many definitions and impacts the minimum schema version for all those definitions?

**Comment by wmunyan** [comment]
David, 
Thanks for starting this, it was something I was just looking at earlier today as well.  From what I understand about the existing process, the minimum schema version was something MITRE did behind-the-scenes and stored the information in their database, and not in the XML itself.  We had an e-mail thread that I found which i think sums up what would be good to do:
1. Add a `<min_schema_version>` element to the existing metadata schema, under `<oval_repository>`
2. Determine if that element should be required for submission

I was considering implementing something that could possibly run nightly (or some schedule) which could re-assess the minimum versions as part of the submission processing, i.e. if an updated "object" (def, tst, obj, ste) is submitted and will be processed in the repo, find affected definitions in order to update their minimum schema version, if necessary.  I believe this was something MITRE already did behind the scenes, so it could be similarly implemented in the CIS repo.

**Comment by blakefrantz** [comment]
Quick notes:
* The [script to detect minimum schema version](https://github.com/CISecurity/OVALRepo/blob/master/scripts/get_min_oval_version.py) is done.  
* The same script updates a given or all definitions(s) with their minimum schema version. It takes ~18 mins to run on the entire repo.
* $0.02: A contributor is encouraged to run the [insert name of magic QA script here] before submitting. This would be a part of that magic.
* $0.02: CIS will run a similar magic QA script on the backend to autocorrect/punt/accept changes

**Comment by DavidRies** [comment]
this looks done... closing...
