### ISSUE TITLE
Assist processing of content recieved via a pull request

### ISSUE THREAD

**Issue by GunnarEngelbach** [CISecurity/OVALRepo#35]
We are building scripts that take standalone content, as contributed from the mailing list, and give a reviewer the tools needed to make a decision about that content before it is merged.

When new/updated content arrives via a pull request, the reviewer needs to have the same ability.  That means using the information in the pull request to determine what content has been contributed, if it passes all the validation requirements, and determine what existing content will be affected.

A proposed process for this is for the reviewer to start with a clone that is in sync with the master, merge the pull request, then use scripts to locate all items that changed due to the pull request, at which point they should be in the same state as if standalone content had been contributed.

Such a script can also do some level of sanity checking, verifying that the local clone is in the proper state.

Simplest solution is to create a script that turns the pull request into a standalone OVAL document and then use the same process as when verifying standalone content -- with the exception that decomposing the content into individual repository files will not need to be done.

Thoughts?  Or a volunteer to write this script?

**Comment by DavidRies** [comment]
This sounds great. Let's pause on the details until we have agreed on the first draft process and can ensure that the script is written to support it.

**Comment by DavidRies** [comment]
I think we've ended up going the opposite direction now that we've settled on a contribution and QA process (see CONTRIBUTIONS.md):
- all QA will be done from within a local working copy of the repo that represents the submission
 - if the submission is a PR, this will be a local topic branch of the master with the PR merged in
 - if the submission is an emailed file, this will be a local topic branch of the master that CIS has decomposed the submission into

So, all the scripts we have (with the exception of the decomposition script) can be written to work against a local copy of the repo with the submission decomposed into element files.

Since this is how the current scripts are written, I am closing this ticket. Feel free to re-open if needed!
