### ISSUE TITLE
Index Revision History for Latest Updates and Stats

### ISSUE THREAD

**Issue by blakefrantz** [CISecurity/OVALRepo#62]
Create something akin to this:
https://oval.mitre.org/repository/data/updates/latest

**Comment by stekel** [comment]
Do we have a python script that can generate this data from the repo?

**Comment by DavidRies** [comment]
We do not. And, our indices aren't set up to handle this nicely. Here's what I recommend:

- we should add a 3rd index for revision_history that has an entry for each contribution with type, date, etc.
- we can use that to get contributor stats by month, quarter, etc.
- we can also use that for getting recently updated definitions

Is that cool with everyone?

**Comment by DavidRies** [comment]
We now have a script for this: web_search_definitions.py with --from date specified. Assigning to Stephen to add page to website.

**Comment by stekel** [comment]
@DavidRies Is there a way to return results that are based on the three categories from the page? (New/Modified/Status Updates)

Also, can we add the "last modified" date to the search results?

**Comment by DavidRies** [comment]
Ok, I've made a a few changes to enable these features:

1. I added last_modified date to results
2. I added a new argument "revision_type" to web_search_definitions.py. You can specify a --from and/or --to date AND a revision_type (status_change, created, submitted, or modified) to get definitions that have been, for example, 'modified' since the supplied --from date.

**Comment by stekel** [comment]
Latest Updates page has been created. Last Modified has been added to search results.
